### ISSUE TITLE
How do I become a contributor for UWC?

### ISSUE THREAD

**Issue by ssbarnea** [AtlassianContribs/universal-wiki-converter#1]
To become a contributor, please add a comment to this issue, so we can see your github account.

**Comment by maboern** [comment]
Hey - I would like to contribute a patch regarding this issue (http://www.weblogism.com/item/288/unmappable-character-for-encoding-utf8) I ran into when trying to  build uwc.

**Comment by ssbarnea** [comment]
I added you to the team, feel free to integrate your contributions. In the future we should build and test it using Travis.

**Comment by fnegre** [comment]
Hello, I would like to report some pull requests from https://bitbucket.org/appfusions/universal-wiki-converter/pull-requests/ to this repo (especially about the problem with JDK 8)
Could you give me access to the project plz ?

**Comment by athompso** [comment]
We're working on a MediaWiki conversion right now, and I believe we will have some changes to contribute when we're done.  -Adam

**Comment by ssbarnea** [comment]
@athompso I added you to the repo as I will probably not have time to work on this too soon and I want to be sure that the project will go on.

**Comment by mathieusaade** [comment]
Hi,

I would like to work on XWiki converter as I need to be able to manage XWiki 2.0 syntax.

Thanks for adding me to the project

Mathieu

**Comment by ssbarnea** [comment]
I am closing but feel free to reopen or comment on it, the list is still open.
